"""Hello World source plugin — Phase 2 end-to-end verification."""

from datetime import date
from typing import List, Dict, Any

from pios.sdk import SourcePlugin, SourceData


class Plugin(SourcePlugin):
    """Minimal source plugin that produces one document.

    Used to verify the full plugin pipeline:
      discover → load → fetch → normalize → save document
    """

    def fetch(self) -> List[SourceData]:
        message = self.context.get_config("message", "Hello from PiOS!")
        today = date.today().isoformat()

        self.logger.info(f"[hello-world] fetch() called, date={today}")

        return [
            SourceData(
                source="source-hello-world",
                data_type="hello-world",
                content={"message": message, "date": today},
                title=f"Hello World — {today}",
                date=today,
                tags=["hello-world", "test"],
            )
        ]

    def normalize(self, data: SourceData) -> Dict[str, Any]:
        return {
            "text": (
                f"# {data.title}\n\n"
                f"{data.content['message']}\n\n"
                f"Generated by PiOS source-hello-world plugin on {data.content['date']}.\n"
            )
        }
